{"version":3,"sources":["../../src/koa/15.js"],"names":["Koa","require","app","error","ctx","throw","use","listen"],"mappings":";;AAAA;;;;;;AAMA,IAAMA,MAAMC,QAAQ,KAAR,CAAZ;AACA,IAAMC,MAAM,IAAIF,GAAJ,EAAZ;;AAEA,IAAMG,QAAQ,SAARA,KAAQ,MAAO;AACnBC,MAAIC,KAAJ,CAAU,GAAV;AACD,CAFD;;AAIAH,IAAII,GAAJ,CAAQH,KAAR;AACAD,IAAIK,MAAJ,CAAW,IAAX","file":"15.js","sourcesContent":["/**\r\n !c 错误处理\r\n ?c 如果代码运行过程中发生错误，我们需要把错误信息返回给用户。\r\n *c HTTP协定约定这时要返回500状态码。KOA提供了ctx.throw()方法，用来抛出错误，看下面的例子：\r\n */\r\n\r\nconst Koa = require('koa')\r\nconst app = new Koa()\r\n\r\nconst error = ctx => {\r\n  ctx.throw(404)\r\n}\r\n\r\napp.use(error)\r\napp.listen(3000)"]}